### ISSUE TITLE
Navigation class, error with utm_to_latlon function

### ISSUE THREAD

**Issue by Nanoseb** [Maritime-Robotics-Student-Society/sailing-robot#95]
For the simulator I need the utm_to_latlon function but I have some errors with it:
the first one:
```
Traceback (most recent call last):
  File "/home/seb/sailing-robot/src/sailing_robot/scripts/simulation_position", line 69, in <module>
    Position_simu()
  File "/home/seb/sailing-robot/src/sailing_robot/scripts/simulation_position", line 39, in __init__
    self.position_publisher()
  File "/home/seb/sailing-robot/src/sailing_robot/scripts/simulation_position", line 60, in position_publisher
    position = self.nav.utm_to_latlon(self.utm_position[0], self.utm_position[1])
  File "/home/seb/sailing-robot/src/sailing_robot/src/sailing_robot/navigation.py", line 39, in utm_to_latlon
    lon, lat = self.projection.inverse(x, y, inverse=True)
AttributeError: 'Proj' object has no attribute 'inverse'
```
can be fixed by removing '.inverse' l39 (there is no mention of this method in the documentation: https://jswhit.github.io/pyproj/pyproj.Proj-class.html)

Then I have the following error
```
Traceback (most recent call last):
  File "/home/seb/sailing-robot/src/sailing_robot/scripts/simulation_position", line 69, in <module>
    Position_simu()
  File "/home/seb/sailing-robot/src/sailing_robot/scripts/simulation_position", line 39, in __init__
    self.position_publisher()
  File "/home/seb/sailing-robot/src/sailing_robot/scripts/simulation_position", line 60, in position_publisher
    position = self.nav.utm_to_latlon(self.utm_position[0], self.utm_position[1])
  File "/home/seb/sailing-robot/src/sailing_robot/src/sailing_robot/navigation.py", line 40, in utm_to_latlon
    return ll.LatLon(lat, lon)
NameError: global name 'll' is not defined
```
And in fact I don't really know how this piece of code is supposed to know `ll`, I managed to get rid of this one by replacing `ll` by `self.position_ll` in this line.

And then I have the error:
```
Traceback (most recent call last):
  File "/home/seb/sailing-robot/src/sailing_robot/scripts/simulation_position", line 69, in <module>
    Position_simu()
  File "/home/seb/sailing-robot/src/sailing_robot/scripts/simulation_position", line 39, in __init__
    self.position_publisher()
  File "/home/seb/sailing-robot/src/sailing_robot/scripts/simulation_position", line 60, in position_publisher
    position = self.nav.utm_to_latlon(self.utm_position[0], self.utm_position[1])
  File "/home/seb/sailing-robot/src/sailing_robot/src/sailing_robot/navigation.py", line 40, in utm_to_latlon
    return self.position_ll.LatLon(lat, lon)
AttributeError: LatLon instance has no attribute 'LatLon'
```

I am now going to bed ;) @takluyver maybe you have an idea on what is wrong with this function.

**Comment by takluyver** [comment]
Thanks - it was a combination of copy-pasting and a method that seemingly wasn't called anywhere. A reminder that even the simplest bit of code benefits from a test.
